/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddAntispamMaildataRequest } from '../models';
// @ts-ignore
import type { CheckAntispamMaildataRulesRequest } from '../models';
// @ts-ignore
import type { CreateAntispamEmailRuleRequest } from '../models';
// @ts-ignore
import type { CreateDnsRecord200Response } from '../models';
/**
 * AntispamApi - axios parameter creator
 */
export const AntispamApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add maildata to antispam engine
         * @param {AddAntispamMaildataRequest} addAntispamMaildataRequest Maildata payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAntispamMaildata: async (addAntispamMaildataRequest: AddAntispamMaildataRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addAntispamMaildataRequest' is not null or undefined
            assertParamExists('addAntispamMaildata', 'addAntispamMaildataRequest', addAntispamMaildataRequest)
            const localVarPath = `/antispam/maildata`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addAntispamMaildataRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Check maildata against existing antispam rules
         * @param {CheckAntispamMaildataRulesRequest} checkAntispamMaildataRulesRequest Maildata payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkAntispamMaildataRules: async (checkAntispamMaildataRulesRequest: CheckAntispamMaildataRulesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'checkAntispamMaildataRulesRequest' is not null or undefined
            assertParamExists('checkAntispamMaildataRules', 'checkAntispamMaildataRulesRequest', checkAntispamMaildataRulesRequest)
            const localVarPath = `/antispam/maildata/check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(checkAntispamMaildataRulesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create antispam email rule or increment existing rule hitcount
         * @param {CreateAntispamEmailRuleRequest} createAntispamEmailRuleRequest Antispam email rule payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAntispamEmailRule: async (createAntispamEmailRuleRequest: CreateAntispamEmailRuleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createAntispamEmailRuleRequest' is not null or undefined
            assertParamExists('createAntispamEmailRule', 'createAntispamEmailRuleRequest', createAntispamEmailRuleRequest)
            const localVarPath = `/antispam/rules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAntispamEmailRuleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AntispamApi - functional programming interface
 */
export const AntispamApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AntispamApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add maildata to antispam engine
         * @param {AddAntispamMaildataRequest} addAntispamMaildataRequest Maildata payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addAntispamMaildata(addAntispamMaildataRequest: AddAntispamMaildataRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addAntispamMaildata(addAntispamMaildataRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AntispamApi.addAntispamMaildata']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Check maildata against existing antispam rules
         * @param {CheckAntispamMaildataRulesRequest} checkAntispamMaildataRulesRequest Maildata payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkAntispamMaildataRules(checkAntispamMaildataRulesRequest: CheckAntispamMaildataRulesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkAntispamMaildataRules(checkAntispamMaildataRulesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AntispamApi.checkAntispamMaildataRules']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create antispam email rule or increment existing rule hitcount
         * @param {CreateAntispamEmailRuleRequest} createAntispamEmailRuleRequest Antispam email rule payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAntispamEmailRule(createAntispamEmailRuleRequest: CreateAntispamEmailRuleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAntispamEmailRule(createAntispamEmailRuleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AntispamApi.createAntispamEmailRule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AntispamApi - factory interface
 */
export const AntispamApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AntispamApiFp(configuration)
    return {
        /**
         * 
         * @summary Add maildata to antispam engine
         * @param {AntispamApiAddAntispamMaildataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAntispamMaildata(requestParameters: AntispamApiAddAntispamMaildataRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.addAntispamMaildata(requestParameters.addAntispamMaildataRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Check maildata against existing antispam rules
         * @param {AntispamApiCheckAntispamMaildataRulesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkAntispamMaildataRules(requestParameters: AntispamApiCheckAntispamMaildataRulesRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.checkAntispamMaildataRules(requestParameters.checkAntispamMaildataRulesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create antispam email rule or increment existing rule hitcount
         * @param {AntispamApiCreateAntispamEmailRuleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAntispamEmailRule(requestParameters: AntispamApiCreateAntispamEmailRuleRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.createAntispamEmailRule(requestParameters.createAntispamEmailRuleRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AntispamApi - interface
 */
export interface AntispamApiInterface {
    /**
     * 
     * @summary Add maildata to antispam engine
     * @param {AntispamApiAddAntispamMaildataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addAntispamMaildata(requestParameters: AntispamApiAddAntispamMaildataRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Check maildata against existing antispam rules
     * @param {AntispamApiCheckAntispamMaildataRulesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkAntispamMaildataRules(requestParameters: AntispamApiCheckAntispamMaildataRulesRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Create antispam email rule or increment existing rule hitcount
     * @param {AntispamApiCreateAntispamEmailRuleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createAntispamEmailRule(requestParameters: AntispamApiCreateAntispamEmailRuleRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

}

/**
 * Request parameters for addAntispamMaildata operation in AntispamApi.
 */
export interface AntispamApiAddAntispamMaildataRequest {
    /**
     * Maildata payload
     */
    readonly addAntispamMaildataRequest: AddAntispamMaildataRequest
}

/**
 * Request parameters for checkAntispamMaildataRules operation in AntispamApi.
 */
export interface AntispamApiCheckAntispamMaildataRulesRequest {
    /**
     * Maildata payload
     */
    readonly checkAntispamMaildataRulesRequest: CheckAntispamMaildataRulesRequest
}

/**
 * Request parameters for createAntispamEmailRule operation in AntispamApi.
 */
export interface AntispamApiCreateAntispamEmailRuleRequest {
    /**
     * Antispam email rule payload
     */
    readonly createAntispamEmailRuleRequest: CreateAntispamEmailRuleRequest
}

/**
 * AntispamApi - object-oriented interface
 */
export class AntispamApi extends BaseAPI implements AntispamApiInterface {
    /**
     * 
     * @summary Add maildata to antispam engine
     * @param {AntispamApiAddAntispamMaildataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addAntispamMaildata(requestParameters: AntispamApiAddAntispamMaildataRequest, options?: RawAxiosRequestConfig) {
        return AntispamApiFp(this.configuration).addAntispamMaildata(requestParameters.addAntispamMaildataRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Check maildata against existing antispam rules
     * @param {AntispamApiCheckAntispamMaildataRulesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public checkAntispamMaildataRules(requestParameters: AntispamApiCheckAntispamMaildataRulesRequest, options?: RawAxiosRequestConfig) {
        return AntispamApiFp(this.configuration).checkAntispamMaildataRules(requestParameters.checkAntispamMaildataRulesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create antispam email rule or increment existing rule hitcount
     * @param {AntispamApiCreateAntispamEmailRuleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createAntispamEmailRule(requestParameters: AntispamApiCreateAntispamEmailRuleRequest, options?: RawAxiosRequestConfig) {
        return AntispamApiFp(this.configuration).createAntispamEmailRule(requestParameters.createAntispamEmailRuleRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

