/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CheckCartCouponRequest } from '../models';
// @ts-ignore
import type { CreateCartItemRequest } from '../models';
// @ts-ignore
import type { CreateDnsRecord200Response } from '../models';
// @ts-ignore
import type { UpdateCartItemCountRequest } from '../models';
// @ts-ignore
import type { UpdateCartItemRequest } from '../models';
/**
 * CartApi - axios parameter creator
 */
export const CartApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check and apply cart coupon
         * @param {CheckCartCouponRequest} checkCartCouponRequest Cart coupon check payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkCartCoupon: async (checkCartCouponRequest: CheckCartCouponRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'checkCartCouponRequest' is not null or undefined
            assertParamExists('checkCartCoupon', 'checkCartCouponRequest', checkCartCouponRequest)
            const localVarPath = `/cart/coupons/check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(checkCartCouponRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add item to cart
         * @param {CreateCartItemRequest} createCartItemRequest Cart item add payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCartItem: async (createCartItemRequest: CreateCartItemRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCartItemRequest' is not null or undefined
            assertParamExists('createCartItem', 'createCartItemRequest', createCartItemRequest)
            const localVarPath = `/cart/items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCartItemRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove item from cart
         * @param {number} cartItemId Cart item ID
         * @param {string} [cname] Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCartItem: async (cartItemId: number, cname?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cartItemId' is not null or undefined
            assertParamExists('deleteCartItem', 'cartItemId', cartItemId)
            const localVarPath = `/cart/items/{cartItemId}`
                .replace(`{${"cartItemId"}}`, encodeURIComponent(String(cartItemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cname !== undefined) {
                localVarQueryParameter['cname'] = cname;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get cart billing address
         * @param {string} [cname] Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCartBillingAddress: async (cname?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cart/billing-address`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cname !== undefined) {
                localVarQueryParameter['cname'] = cname;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get current cart coupon
         * @param {string} [cname] Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCartCoupon: async (cname?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cart/coupons/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cname !== undefined) {
                localVarQueryParameter['cname'] = cname;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get cart total
         * @param {string} [cname] Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCartTotal: async (cname?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cart/total`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cname !== undefined) {
                localVarQueryParameter['cname'] = cname;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List cart items
         * @param {string} [cname] Customer name
         * @param {string} [lang] Response language
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCartItems: async (cname?: string, lang?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cart/items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cname !== undefined) {
                localVarQueryParameter['cname'] = cname;
            }

            if (lang !== undefined) {
                localVarQueryParameter['lang'] = lang;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update cart item data
         * @param {number} cartItemId Cart item ID
         * @param {UpdateCartItemRequest} updateCartItemRequest Cart item update payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCartItem: async (cartItemId: number, updateCartItemRequest: UpdateCartItemRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cartItemId' is not null or undefined
            assertParamExists('updateCartItem', 'cartItemId', cartItemId)
            // verify required parameter 'updateCartItemRequest' is not null or undefined
            assertParamExists('updateCartItem', 'updateCartItemRequest', updateCartItemRequest)
            const localVarPath = `/cart/items/{cartItemId}`
                .replace(`{${"cartItemId"}}`, encodeURIComponent(String(cartItemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCartItemRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update cart item count by product and domain
         * @param {UpdateCartItemCountRequest} updateCartItemCountRequest Cart item count update payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCartItemCount: async (updateCartItemCountRequest: UpdateCartItemCountRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateCartItemCountRequest' is not null or undefined
            assertParamExists('updateCartItemCount', 'updateCartItemCountRequest', updateCartItemCountRequest)
            const localVarPath = `/cart/items/by-product/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCartItemCountRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CartApi - functional programming interface
 */
export const CartApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CartApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Check and apply cart coupon
         * @param {CheckCartCouponRequest} checkCartCouponRequest Cart coupon check payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkCartCoupon(checkCartCouponRequest: CheckCartCouponRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkCartCoupon(checkCartCouponRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.checkCartCoupon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add item to cart
         * @param {CreateCartItemRequest} createCartItemRequest Cart item add payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCartItem(createCartItemRequest: CreateCartItemRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCartItem(createCartItemRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.createCartItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remove item from cart
         * @param {number} cartItemId Cart item ID
         * @param {string} [cname] Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCartItem(cartItemId: number, cname?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCartItem(cartItemId, cname, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.deleteCartItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get cart billing address
         * @param {string} [cname] Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCartBillingAddress(cname?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCartBillingAddress(cname, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.getCartBillingAddress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get current cart coupon
         * @param {string} [cname] Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCartCoupon(cname?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCartCoupon(cname, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.getCartCoupon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get cart total
         * @param {string} [cname] Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCartTotal(cname?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCartTotal(cname, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.getCartTotal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List cart items
         * @param {string} [cname] Customer name
         * @param {string} [lang] Response language
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCartItems(cname?: string, lang?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCartItems(cname, lang, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.listCartItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update cart item data
         * @param {number} cartItemId Cart item ID
         * @param {UpdateCartItemRequest} updateCartItemRequest Cart item update payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCartItem(cartItemId: number, updateCartItemRequest: UpdateCartItemRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCartItem(cartItemId, updateCartItemRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.updateCartItem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update cart item count by product and domain
         * @param {UpdateCartItemCountRequest} updateCartItemCountRequest Cart item count update payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCartItemCount(updateCartItemCountRequest: UpdateCartItemCountRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCartItemCount(updateCartItemCountRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CartApi.updateCartItemCount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CartApi - factory interface
 */
export const CartApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CartApiFp(configuration)
    return {
        /**
         * 
         * @summary Check and apply cart coupon
         * @param {CartApiCheckCartCouponRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkCartCoupon(requestParameters: CartApiCheckCartCouponRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.checkCartCoupon(requestParameters.checkCartCouponRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add item to cart
         * @param {CartApiCreateCartItemRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCartItem(requestParameters: CartApiCreateCartItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.createCartItem(requestParameters.createCartItemRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove item from cart
         * @param {CartApiDeleteCartItemRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCartItem(requestParameters: CartApiDeleteCartItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.deleteCartItem(requestParameters.cartItemId, requestParameters.cname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get cart billing address
         * @param {CartApiGetCartBillingAddressRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCartBillingAddress(requestParameters: CartApiGetCartBillingAddressRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.getCartBillingAddress(requestParameters.cname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get current cart coupon
         * @param {CartApiGetCartCouponRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCartCoupon(requestParameters: CartApiGetCartCouponRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.getCartCoupon(requestParameters.cname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get cart total
         * @param {CartApiGetCartTotalRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCartTotal(requestParameters: CartApiGetCartTotalRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.getCartTotal(requestParameters.cname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List cart items
         * @param {CartApiListCartItemsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCartItems(requestParameters: CartApiListCartItemsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.listCartItems(requestParameters.cname, requestParameters.lang, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update cart item data
         * @param {CartApiUpdateCartItemRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCartItem(requestParameters: CartApiUpdateCartItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.updateCartItem(requestParameters.cartItemId, requestParameters.updateCartItemRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update cart item count by product and domain
         * @param {CartApiUpdateCartItemCountRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCartItemCount(requestParameters: CartApiUpdateCartItemCountRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.updateCartItemCount(requestParameters.updateCartItemCountRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CartApi - interface
 */
export interface CartApiInterface {
    /**
     * 
     * @summary Check and apply cart coupon
     * @param {CartApiCheckCartCouponRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkCartCoupon(requestParameters: CartApiCheckCartCouponRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Add item to cart
     * @param {CartApiCreateCartItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCartItem(requestParameters: CartApiCreateCartItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Remove item from cart
     * @param {CartApiDeleteCartItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCartItem(requestParameters: CartApiDeleteCartItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Get cart billing address
     * @param {CartApiGetCartBillingAddressRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCartBillingAddress(requestParameters?: CartApiGetCartBillingAddressRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Get current cart coupon
     * @param {CartApiGetCartCouponRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCartCoupon(requestParameters?: CartApiGetCartCouponRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Get cart total
     * @param {CartApiGetCartTotalRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCartTotal(requestParameters?: CartApiGetCartTotalRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary List cart items
     * @param {CartApiListCartItemsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCartItems(requestParameters?: CartApiListCartItemsRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Update cart item data
     * @param {CartApiUpdateCartItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCartItem(requestParameters: CartApiUpdateCartItemRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Update cart item count by product and domain
     * @param {CartApiUpdateCartItemCountRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCartItemCount(requestParameters: CartApiUpdateCartItemCountRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

}

/**
 * Request parameters for checkCartCoupon operation in CartApi.
 */
export interface CartApiCheckCartCouponRequest {
    /**
     * Cart coupon check payload
     */
    readonly checkCartCouponRequest: CheckCartCouponRequest
}

/**
 * Request parameters for createCartItem operation in CartApi.
 */
export interface CartApiCreateCartItemRequest {
    /**
     * Cart item add payload
     */
    readonly createCartItemRequest: CreateCartItemRequest
}

/**
 * Request parameters for deleteCartItem operation in CartApi.
 */
export interface CartApiDeleteCartItemRequest {
    /**
     * Cart item ID
     */
    readonly cartItemId: number

    /**
     * Customer name
     */
    readonly cname?: string
}

/**
 * Request parameters for getCartBillingAddress operation in CartApi.
 */
export interface CartApiGetCartBillingAddressRequest {
    /**
     * Customer name
     */
    readonly cname?: string
}

/**
 * Request parameters for getCartCoupon operation in CartApi.
 */
export interface CartApiGetCartCouponRequest {
    /**
     * Customer name
     */
    readonly cname?: string
}

/**
 * Request parameters for getCartTotal operation in CartApi.
 */
export interface CartApiGetCartTotalRequest {
    /**
     * Customer name
     */
    readonly cname?: string
}

/**
 * Request parameters for listCartItems operation in CartApi.
 */
export interface CartApiListCartItemsRequest {
    /**
     * Customer name
     */
    readonly cname?: string

    /**
     * Response language
     */
    readonly lang?: string
}

/**
 * Request parameters for updateCartItem operation in CartApi.
 */
export interface CartApiUpdateCartItemRequest {
    /**
     * Cart item ID
     */
    readonly cartItemId: number

    /**
     * Cart item update payload
     */
    readonly updateCartItemRequest: UpdateCartItemRequest
}

/**
 * Request parameters for updateCartItemCount operation in CartApi.
 */
export interface CartApiUpdateCartItemCountRequest {
    /**
     * Cart item count update payload
     */
    readonly updateCartItemCountRequest: UpdateCartItemCountRequest
}

/**
 * CartApi - object-oriented interface
 */
export class CartApi extends BaseAPI implements CartApiInterface {
    /**
     * 
     * @summary Check and apply cart coupon
     * @param {CartApiCheckCartCouponRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public checkCartCoupon(requestParameters: CartApiCheckCartCouponRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).checkCartCoupon(requestParameters.checkCartCouponRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add item to cart
     * @param {CartApiCreateCartItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCartItem(requestParameters: CartApiCreateCartItemRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).createCartItem(requestParameters.createCartItemRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove item from cart
     * @param {CartApiDeleteCartItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCartItem(requestParameters: CartApiDeleteCartItemRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).deleteCartItem(requestParameters.cartItemId, requestParameters.cname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get cart billing address
     * @param {CartApiGetCartBillingAddressRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCartBillingAddress(requestParameters: CartApiGetCartBillingAddressRequest = {}, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).getCartBillingAddress(requestParameters.cname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get current cart coupon
     * @param {CartApiGetCartCouponRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCartCoupon(requestParameters: CartApiGetCartCouponRequest = {}, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).getCartCoupon(requestParameters.cname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get cart total
     * @param {CartApiGetCartTotalRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCartTotal(requestParameters: CartApiGetCartTotalRequest = {}, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).getCartTotal(requestParameters.cname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List cart items
     * @param {CartApiListCartItemsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listCartItems(requestParameters: CartApiListCartItemsRequest = {}, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).listCartItems(requestParameters.cname, requestParameters.lang, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update cart item data
     * @param {CartApiUpdateCartItemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCartItem(requestParameters: CartApiUpdateCartItemRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).updateCartItem(requestParameters.cartItemId, requestParameters.updateCartItemRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update cart item count by product and domain
     * @param {CartApiUpdateCartItemCountRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCartItemCount(requestParameters: CartApiUpdateCartItemCountRequest, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).updateCartItemCount(requestParameters.updateCartItemCountRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

