/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateDnsRecord200Response } from '../models';
// @ts-ignore
import type { CreateDnsRecordRequest } from '../models';
// @ts-ignore
import type { GetDnsRecords200Response } from '../models';
// @ts-ignore
import type { UpdateDnsRecordRequest } from '../models';
/**
 * DNSApi - axios parameter creator
 */
export const DNSApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create DNS record
         * @param {string} domain Domain name
         * @param {CreateDnsRecordRequest} createDnsRecordRequest DNS record payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDnsRecord: async (domain: string, createDnsRecordRequest: CreateDnsRecordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('createDnsRecord', 'domain', domain)
            // verify required parameter 'createDnsRecordRequest' is not null or undefined
            assertParamExists('createDnsRecord', 'createDnsRecordRequest', createDnsRecordRequest)
            const localVarPath = `/dns/{domain}/records`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createDnsRecordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete DNS record
         * @param {string} domain Domain name
         * @param {number} recordId Record ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDnsRecord: async (domain: string, recordId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('deleteDnsRecord', 'domain', domain)
            // verify required parameter 'recordId' is not null or undefined
            assertParamExists('deleteDnsRecord', 'recordId', recordId)
            const localVarPath = `/dns/{domain}/records/{recordId}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)))
                .replace(`{${"recordId"}}`, encodeURIComponent(String(recordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get DNS records by domain
         * @param {string} domain Domain name
         * @param {string} [type] Filter records by type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDnsRecords: async (domain: string, type?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('getDnsRecords', 'domain', domain)
            const localVarPath = `/dns/{domain}/records`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update DNS record
         * @param {string} domain Domain name
         * @param {number} recordId Record ID
         * @param {UpdateDnsRecordRequest} updateDnsRecordRequest Partial DNS record payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDnsRecord: async (domain: string, recordId: number, updateDnsRecordRequest: UpdateDnsRecordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('updateDnsRecord', 'domain', domain)
            // verify required parameter 'recordId' is not null or undefined
            assertParamExists('updateDnsRecord', 'recordId', recordId)
            // verify required parameter 'updateDnsRecordRequest' is not null or undefined
            assertParamExists('updateDnsRecord', 'updateDnsRecordRequest', updateDnsRecordRequest)
            const localVarPath = `/dns/{domain}/records/{recordId}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)))
                .replace(`{${"recordId"}}`, encodeURIComponent(String(recordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateDnsRecordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DNSApi - functional programming interface
 */
export const DNSApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DNSApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create DNS record
         * @param {string} domain Domain name
         * @param {CreateDnsRecordRequest} createDnsRecordRequest DNS record payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDnsRecord(domain: string, createDnsRecordRequest: CreateDnsRecordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDnsRecord(domain, createDnsRecordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DNSApi.createDnsRecord']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete DNS record
         * @param {string} domain Domain name
         * @param {number} recordId Record ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDnsRecord(domain: string, recordId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDnsRecord(domain, recordId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DNSApi.deleteDnsRecord']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get DNS records by domain
         * @param {string} domain Domain name
         * @param {string} [type] Filter records by type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDnsRecords(domain: string, type?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetDnsRecords200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDnsRecords(domain, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DNSApi.getDnsRecords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update DNS record
         * @param {string} domain Domain name
         * @param {number} recordId Record ID
         * @param {UpdateDnsRecordRequest} updateDnsRecordRequest Partial DNS record payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDnsRecord(domain: string, recordId: number, updateDnsRecordRequest: UpdateDnsRecordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDnsRecord(domain, recordId, updateDnsRecordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DNSApi.updateDnsRecord']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DNSApi - factory interface
 */
export const DNSApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DNSApiFp(configuration)
    return {
        /**
         * 
         * @summary Create DNS record
         * @param {DNSApiCreateDnsRecordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDnsRecord(requestParameters: DNSApiCreateDnsRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.createDnsRecord(requestParameters.domain, requestParameters.createDnsRecordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete DNS record
         * @param {DNSApiDeleteDnsRecordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDnsRecord(requestParameters: DNSApiDeleteDnsRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.deleteDnsRecord(requestParameters.domain, requestParameters.recordId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get DNS records by domain
         * @param {DNSApiGetDnsRecordsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDnsRecords(requestParameters: DNSApiGetDnsRecordsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetDnsRecords200Response> {
            return localVarFp.getDnsRecords(requestParameters.domain, requestParameters.type, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update DNS record
         * @param {DNSApiUpdateDnsRecordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDnsRecord(requestParameters: DNSApiUpdateDnsRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.updateDnsRecord(requestParameters.domain, requestParameters.recordId, requestParameters.updateDnsRecordRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DNSApi - interface
 */
export interface DNSApiInterface {
    /**
     * 
     * @summary Create DNS record
     * @param {DNSApiCreateDnsRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDnsRecord(requestParameters: DNSApiCreateDnsRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Delete DNS record
     * @param {DNSApiDeleteDnsRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteDnsRecord(requestParameters: DNSApiDeleteDnsRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Get DNS records by domain
     * @param {DNSApiGetDnsRecordsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDnsRecords(requestParameters: DNSApiGetDnsRecordsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetDnsRecords200Response>;

    /**
     * 
     * @summary Update DNS record
     * @param {DNSApiUpdateDnsRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateDnsRecord(requestParameters: DNSApiUpdateDnsRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

}

/**
 * Request parameters for createDnsRecord operation in DNSApi.
 */
export interface DNSApiCreateDnsRecordRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * DNS record payload
     */
    readonly createDnsRecordRequest: CreateDnsRecordRequest
}

/**
 * Request parameters for deleteDnsRecord operation in DNSApi.
 */
export interface DNSApiDeleteDnsRecordRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Record ID
     */
    readonly recordId: number
}

/**
 * Request parameters for getDnsRecords operation in DNSApi.
 */
export interface DNSApiGetDnsRecordsRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Filter records by type
     */
    readonly type?: string
}

/**
 * Request parameters for updateDnsRecord operation in DNSApi.
 */
export interface DNSApiUpdateDnsRecordRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Record ID
     */
    readonly recordId: number

    /**
     * Partial DNS record payload
     */
    readonly updateDnsRecordRequest: UpdateDnsRecordRequest
}

/**
 * DNSApi - object-oriented interface
 */
export class DNSApi extends BaseAPI implements DNSApiInterface {
    /**
     * 
     * @summary Create DNS record
     * @param {DNSApiCreateDnsRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDnsRecord(requestParameters: DNSApiCreateDnsRecordRequest, options?: RawAxiosRequestConfig) {
        return DNSApiFp(this.configuration).createDnsRecord(requestParameters.domain, requestParameters.createDnsRecordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete DNS record
     * @param {DNSApiDeleteDnsRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDnsRecord(requestParameters: DNSApiDeleteDnsRecordRequest, options?: RawAxiosRequestConfig) {
        return DNSApiFp(this.configuration).deleteDnsRecord(requestParameters.domain, requestParameters.recordId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get DNS records by domain
     * @param {DNSApiGetDnsRecordsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDnsRecords(requestParameters: DNSApiGetDnsRecordsRequest, options?: RawAxiosRequestConfig) {
        return DNSApiFp(this.configuration).getDnsRecords(requestParameters.domain, requestParameters.type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update DNS record
     * @param {DNSApiUpdateDnsRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateDnsRecord(requestParameters: DNSApiUpdateDnsRecordRequest, options?: RawAxiosRequestConfig) {
        return DNSApiFp(this.configuration).updateDnsRecord(requestParameters.domain, requestParameters.recordId, requestParameters.updateDnsRecordRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

