/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ChangeDomainNameserversRequest } from '../models';
// @ts-ignore
import type { CreateDnsRecord200Response } from '../models';
// @ts-ignore
import type { ListDomains200Response } from '../models';
// @ts-ignore
import type { RegisterDomainRequest } from '../models';
// @ts-ignore
import type { RenewDomainRequest } from '../models';
/**
 * DomainApi - axios parameter creator
 */
export const DomainApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Change domain nameservers
         * @param {string} domain Domain name
         * @param {ChangeDomainNameserversRequest} changeDomainNameserversRequest Nameserver payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeDomainNameservers: async (domain: string, changeDomainNameserversRequest: ChangeDomainNameserversRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('changeDomainNameservers', 'domain', domain)
            // verify required parameter 'changeDomainNameserversRequest' is not null or undefined
            assertParamExists('changeDomainNameservers', 'changeDomainNameserversRequest', changeDomainNameserversRequest)
            const localVarPath = `/domains/{domain}/nameservers`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changeDomainNameserversRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Close external customer domain product
         * @param {string} domain Domain name
         * @param {string} cname Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeDomain: async (domain: string, cname: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('closeDomain', 'domain', domain)
            // verify required parameter 'cname' is not null or undefined
            assertParamExists('closeDomain', 'cname', cname)
            const localVarPath = `/domains/{domain}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cname !== undefined) {
                localVarQueryParameter['cname'] = cname;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get domain information and availability
         * @param {string} domain Domain name
         * @param {string} [cname] Customer name for product context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDomainInfo: async (domain: string, cname?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('getDomainInfo', 'domain', domain)
            const localVarPath = `/domains/{domain}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cname !== undefined) {
                localVarQueryParameter['cname'] = cname;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List customer domains
         * @param {string} cname Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDomains: async (cname: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cname' is not null or undefined
            assertParamExists('listDomains', 'cname', cname)
            const localVarPath = `/domains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cname !== undefined) {
                localVarQueryParameter['cname'] = cname;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register domain
         * @param {string} domain Domain name
         * @param {RegisterDomainRequest} registerDomainRequest Domain registration payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerDomain: async (domain: string, registerDomainRequest: RegisterDomainRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('registerDomain', 'domain', domain)
            // verify required parameter 'registerDomainRequest' is not null or undefined
            assertParamExists('registerDomain', 'registerDomainRequest', registerDomainRequest)
            const localVarPath = `/domains/{domain}/register`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerDomainRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Renew domain
         * @param {string} domain Domain name
         * @param {RenewDomainRequest} [renewDomainRequest] Domain renewal payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renewDomain: async (domain: string, renewDomainRequest?: RenewDomainRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('renewDomain', 'domain', domain)
            const localVarPath = `/domains/{domain}/renew`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(renewDomainRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DomainApi - functional programming interface
 */
export const DomainApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DomainApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Change domain nameservers
         * @param {string} domain Domain name
         * @param {ChangeDomainNameserversRequest} changeDomainNameserversRequest Nameserver payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changeDomainNameservers(domain: string, changeDomainNameserversRequest: ChangeDomainNameserversRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changeDomainNameservers(domain, changeDomainNameserversRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainApi.changeDomainNameservers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Close external customer domain product
         * @param {string} domain Domain name
         * @param {string} cname Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async closeDomain(domain: string, cname: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.closeDomain(domain, cname, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainApi.closeDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get domain information and availability
         * @param {string} domain Domain name
         * @param {string} [cname] Customer name for product context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDomainInfo(domain: string, cname?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDomainInfo(domain, cname, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainApi.getDomainInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List customer domains
         * @param {string} cname Customer name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDomains(cname: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListDomains200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDomains(cname, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainApi.listDomains']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register domain
         * @param {string} domain Domain name
         * @param {RegisterDomainRequest} registerDomainRequest Domain registration payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerDomain(domain: string, registerDomainRequest: RegisterDomainRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerDomain(domain, registerDomainRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainApi.registerDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Renew domain
         * @param {string} domain Domain name
         * @param {RenewDomainRequest} [renewDomainRequest] Domain renewal payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async renewDomain(domain: string, renewDomainRequest?: RenewDomainRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.renewDomain(domain, renewDomainRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainApi.renewDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DomainApi - factory interface
 */
export const DomainApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DomainApiFp(configuration)
    return {
        /**
         * 
         * @summary Change domain nameservers
         * @param {DomainApiChangeDomainNameserversRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeDomainNameservers(requestParameters: DomainApiChangeDomainNameserversRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.changeDomainNameservers(requestParameters.domain, requestParameters.changeDomainNameserversRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Close external customer domain product
         * @param {DomainApiCloseDomainRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeDomain(requestParameters: DomainApiCloseDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.closeDomain(requestParameters.domain, requestParameters.cname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get domain information and availability
         * @param {DomainApiGetDomainInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDomainInfo(requestParameters: DomainApiGetDomainInfoRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.getDomainInfo(requestParameters.domain, requestParameters.cname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List customer domains
         * @param {DomainApiListDomainsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDomains(requestParameters: DomainApiListDomainsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListDomains200Response> {
            return localVarFp.listDomains(requestParameters.cname, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register domain
         * @param {DomainApiRegisterDomainRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerDomain(requestParameters: DomainApiRegisterDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.registerDomain(requestParameters.domain, requestParameters.registerDomainRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Renew domain
         * @param {DomainApiRenewDomainRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renewDomain(requestParameters: DomainApiRenewDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.renewDomain(requestParameters.domain, requestParameters.renewDomainRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DomainApi - interface
 */
export interface DomainApiInterface {
    /**
     * 
     * @summary Change domain nameservers
     * @param {DomainApiChangeDomainNameserversRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeDomainNameservers(requestParameters: DomainApiChangeDomainNameserversRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Close external customer domain product
     * @param {DomainApiCloseDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    closeDomain(requestParameters: DomainApiCloseDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Get domain information and availability
     * @param {DomainApiGetDomainInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDomainInfo(requestParameters: DomainApiGetDomainInfoRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary List customer domains
     * @param {DomainApiListDomainsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDomains(requestParameters: DomainApiListDomainsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListDomains200Response>;

    /**
     * 
     * @summary Register domain
     * @param {DomainApiRegisterDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerDomain(requestParameters: DomainApiRegisterDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Renew domain
     * @param {DomainApiRenewDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    renewDomain(requestParameters: DomainApiRenewDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

}

/**
 * Request parameters for changeDomainNameservers operation in DomainApi.
 */
export interface DomainApiChangeDomainNameserversRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Nameserver payload
     */
    readonly changeDomainNameserversRequest: ChangeDomainNameserversRequest
}

/**
 * Request parameters for closeDomain operation in DomainApi.
 */
export interface DomainApiCloseDomainRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Customer name
     */
    readonly cname: string
}

/**
 * Request parameters for getDomainInfo operation in DomainApi.
 */
export interface DomainApiGetDomainInfoRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Customer name for product context
     */
    readonly cname?: string
}

/**
 * Request parameters for listDomains operation in DomainApi.
 */
export interface DomainApiListDomainsRequest {
    /**
     * Customer name
     */
    readonly cname: string
}

/**
 * Request parameters for registerDomain operation in DomainApi.
 */
export interface DomainApiRegisterDomainRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Domain registration payload
     */
    readonly registerDomainRequest: RegisterDomainRequest
}

/**
 * Request parameters for renewDomain operation in DomainApi.
 */
export interface DomainApiRenewDomainRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Domain renewal payload
     */
    readonly renewDomainRequest?: RenewDomainRequest
}

/**
 * DomainApi - object-oriented interface
 */
export class DomainApi extends BaseAPI implements DomainApiInterface {
    /**
     * 
     * @summary Change domain nameservers
     * @param {DomainApiChangeDomainNameserversRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public changeDomainNameservers(requestParameters: DomainApiChangeDomainNameserversRequest, options?: RawAxiosRequestConfig) {
        return DomainApiFp(this.configuration).changeDomainNameservers(requestParameters.domain, requestParameters.changeDomainNameserversRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Close external customer domain product
     * @param {DomainApiCloseDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public closeDomain(requestParameters: DomainApiCloseDomainRequest, options?: RawAxiosRequestConfig) {
        return DomainApiFp(this.configuration).closeDomain(requestParameters.domain, requestParameters.cname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get domain information and availability
     * @param {DomainApiGetDomainInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDomainInfo(requestParameters: DomainApiGetDomainInfoRequest, options?: RawAxiosRequestConfig) {
        return DomainApiFp(this.configuration).getDomainInfo(requestParameters.domain, requestParameters.cname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List customer domains
     * @param {DomainApiListDomainsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDomains(requestParameters: DomainApiListDomainsRequest, options?: RawAxiosRequestConfig) {
        return DomainApiFp(this.configuration).listDomains(requestParameters.cname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register domain
     * @param {DomainApiRegisterDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerDomain(requestParameters: DomainApiRegisterDomainRequest, options?: RawAxiosRequestConfig) {
        return DomainApiFp(this.configuration).registerDomain(requestParameters.domain, requestParameters.registerDomainRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Renew domain
     * @param {DomainApiRenewDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public renewDomain(requestParameters: DomainApiRenewDomainRequest, options?: RawAxiosRequestConfig) {
        return DomainApiFp(this.configuration).renewDomain(requestParameters.domain, requestParameters.renewDomainRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

