/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ChangeMailboxPasswordRequest } from '../models';
// @ts-ignore
import type { CreateDnsRecord200Response } from '../models';
// @ts-ignore
import type { CreateMailboxRequest } from '../models';
/**
 * EmailApi - axios parameter creator
 */
export const EmailApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Change mailbox password
         * @param {string} domain Domain name
         * @param {string} username Mailbox username
         * @param {ChangeMailboxPasswordRequest} changeMailboxPasswordRequest Mailbox password payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeMailboxPassword: async (domain: string, username: string, changeMailboxPasswordRequest: ChangeMailboxPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('changeMailboxPassword', 'domain', domain)
            // verify required parameter 'username' is not null or undefined
            assertParamExists('changeMailboxPassword', 'username', username)
            // verify required parameter 'changeMailboxPasswordRequest' is not null or undefined
            assertParamExists('changeMailboxPassword', 'changeMailboxPasswordRequest', changeMailboxPasswordRequest)
            const localVarPath = `/email/{domain}/mailboxes/{username}/password`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)))
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changeMailboxPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create mailbox
         * @param {string} domain Domain name
         * @param {CreateMailboxRequest} createMailboxRequest Mailbox payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMailbox: async (domain: string, createMailboxRequest: CreateMailboxRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('createMailbox', 'domain', domain)
            // verify required parameter 'createMailboxRequest' is not null or undefined
            assertParamExists('createMailbox', 'createMailboxRequest', createMailboxRequest)
            const localVarPath = `/email/{domain}/mailboxes`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMailboxRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmailApi - functional programming interface
 */
export const EmailApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmailApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Change mailbox password
         * @param {string} domain Domain name
         * @param {string} username Mailbox username
         * @param {ChangeMailboxPasswordRequest} changeMailboxPasswordRequest Mailbox password payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changeMailboxPassword(domain: string, username: string, changeMailboxPasswordRequest: ChangeMailboxPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changeMailboxPassword(domain, username, changeMailboxPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailApi.changeMailboxPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create mailbox
         * @param {string} domain Domain name
         * @param {CreateMailboxRequest} createMailboxRequest Mailbox payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMailbox(domain: string, createMailboxRequest: CreateMailboxRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMailbox(domain, createMailboxRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailApi.createMailbox']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EmailApi - factory interface
 */
export const EmailApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmailApiFp(configuration)
    return {
        /**
         * 
         * @summary Change mailbox password
         * @param {EmailApiChangeMailboxPasswordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeMailboxPassword(requestParameters: EmailApiChangeMailboxPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.changeMailboxPassword(requestParameters.domain, requestParameters.username, requestParameters.changeMailboxPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create mailbox
         * @param {EmailApiCreateMailboxRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMailbox(requestParameters: EmailApiCreateMailboxRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.createMailbox(requestParameters.domain, requestParameters.createMailboxRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmailApi - interface
 */
export interface EmailApiInterface {
    /**
     * 
     * @summary Change mailbox password
     * @param {EmailApiChangeMailboxPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    changeMailboxPassword(requestParameters: EmailApiChangeMailboxPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Create mailbox
     * @param {EmailApiCreateMailboxRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createMailbox(requestParameters: EmailApiCreateMailboxRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

}

/**
 * Request parameters for changeMailboxPassword operation in EmailApi.
 */
export interface EmailApiChangeMailboxPasswordRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Mailbox username
     */
    readonly username: string

    /**
     * Mailbox password payload
     */
    readonly changeMailboxPasswordRequest: ChangeMailboxPasswordRequest
}

/**
 * Request parameters for createMailbox operation in EmailApi.
 */
export interface EmailApiCreateMailboxRequest {
    /**
     * Domain name
     */
    readonly domain: string

    /**
     * Mailbox payload
     */
    readonly createMailboxRequest: CreateMailboxRequest
}

/**
 * EmailApi - object-oriented interface
 */
export class EmailApi extends BaseAPI implements EmailApiInterface {
    /**
     * 
     * @summary Change mailbox password
     * @param {EmailApiChangeMailboxPasswordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public changeMailboxPassword(requestParameters: EmailApiChangeMailboxPasswordRequest, options?: RawAxiosRequestConfig) {
        return EmailApiFp(this.configuration).changeMailboxPassword(requestParameters.domain, requestParameters.username, requestParameters.changeMailboxPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create mailbox
     * @param {EmailApiCreateMailboxRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createMailbox(requestParameters: EmailApiCreateMailboxRequest, options?: RawAxiosRequestConfig) {
        return EmailApiFp(this.configuration).createMailbox(requestParameters.domain, requestParameters.createMailboxRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

