/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SpamDetection200Response } from '../models';
// @ts-ignore
import type { SpamDetectionRequest } from '../models';
/**
 * LLMApi - axios parameter creator
 */
export const LLMApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Classify a web form message as spam or ham using the local LLM
         * @param {SpamDetectionRequest} spamDetectionRequest Spam detection payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spamDetection: async (spamDetectionRequest: SpamDetectionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spamDetectionRequest' is not null or undefined
            assertParamExists('spamDetection', 'spamDetectionRequest', spamDetectionRequest)
            const localVarPath = `/llm/spam-detection`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(spamDetectionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LLMApi - functional programming interface
 */
export const LLMApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LLMApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Classify a web form message as spam or ham using the local LLM
         * @param {SpamDetectionRequest} spamDetectionRequest Spam detection payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async spamDetection(spamDetectionRequest: SpamDetectionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpamDetection200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.spamDetection(spamDetectionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LLMApi.spamDetection']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LLMApi - factory interface
 */
export const LLMApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LLMApiFp(configuration)
    return {
        /**
         * 
         * @summary Classify a web form message as spam or ham using the local LLM
         * @param {LLMApiSpamDetectionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        spamDetection(requestParameters: LLMApiSpamDetectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<SpamDetection200Response> {
            return localVarFp.spamDetection(requestParameters.spamDetectionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LLMApi - interface
 */
export interface LLMApiInterface {
    /**
     * 
     * @summary Classify a web form message as spam or ham using the local LLM
     * @param {LLMApiSpamDetectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    spamDetection(requestParameters: LLMApiSpamDetectionRequest, options?: RawAxiosRequestConfig): AxiosPromise<SpamDetection200Response>;

}

/**
 * Request parameters for spamDetection operation in LLMApi.
 */
export interface LLMApiSpamDetectionRequest {
    /**
     * Spam detection payload
     */
    readonly spamDetectionRequest: SpamDetectionRequest
}

/**
 * LLMApi - object-oriented interface
 */
export class LLMApi extends BaseAPI implements LLMApiInterface {
    /**
     * 
     * @summary Classify a web form message as spam or ham using the local LLM
     * @param {LLMApiSpamDetectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public spamDetection(requestParameters: LLMApiSpamDetectionRequest, options?: RawAxiosRequestConfig) {
        return LLMApiFp(this.configuration).spamDetection(requestParameters.spamDetectionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

