/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateOauthRequest200Response } from '../models';
// @ts-ignore
import type { CreateOauthRequestRequest } from '../models';
// @ts-ignore
import type { DeleteOauthToken200Response } from '../models';
// @ts-ignore
import type { GetOauthScopes200Response } from '../models';
// @ts-ignore
import type { RefreshOauthTokenRequest } from '../models';
// @ts-ignore
import type { VerifyOauthRequest200Response } from '../models';
/**
 * OAuthApi - axios parameter creator
 */
export const OAuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create OAuth request
         * @param {CreateOauthRequestRequest} [createOauthRequestRequest] OAuth create payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOauthRequest: async (createOauthRequestRequest?: CreateOauthRequestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/oauth/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createOauthRequestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete OAuth token
         * @param {string} token OAuth token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOauthToken: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('deleteOauthToken', 'token', token)
            const localVarPath = `/oauth/tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List available OAuth scopes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOauthScopes: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/oauth/scopes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh OAuth token
         * @param {RefreshOauthTokenRequest} refreshOauthTokenRequest OAuth refresh payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshOauthToken: async (refreshOauthTokenRequest: RefreshOauthTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refreshOauthTokenRequest' is not null or undefined
            assertParamExists('refreshOauthToken', 'refreshOauthTokenRequest', refreshOauthTokenRequest)
            const localVarPath = `/oauth/tokens/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(refreshOauthTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify OAuth request
         * @param {string} verifyToken Verify token from OAuth create response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyOauthRequest: async (verifyToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verifyToken' is not null or undefined
            assertParamExists('verifyOauthRequest', 'verifyToken', verifyToken)
            const localVarPath = `/oauth/requests/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (verifyToken !== undefined) {
                localVarQueryParameter['verify_token'] = verifyToken;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OAuthApi - functional programming interface
 */
export const OAuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OAuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create OAuth request
         * @param {CreateOauthRequestRequest} [createOauthRequestRequest] OAuth create payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOauthRequest(createOauthRequestRequest?: CreateOauthRequestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOauthRequest200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOauthRequest(createOauthRequestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OAuthApi.createOauthRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete OAuth token
         * @param {string} token OAuth token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOauthToken(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteOauthToken200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOauthToken(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OAuthApi.deleteOauthToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List available OAuth scopes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOauthScopes(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetOauthScopes200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOauthScopes(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OAuthApi.getOauthScopes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh OAuth token
         * @param {RefreshOauthTokenRequest} refreshOauthTokenRequest OAuth refresh payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshOauthToken(refreshOauthTokenRequest: RefreshOauthTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VerifyOauthRequest200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshOauthToken(refreshOauthTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OAuthApi.refreshOauthToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Verify OAuth request
         * @param {string} verifyToken Verify token from OAuth create response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyOauthRequest(verifyToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VerifyOauthRequest200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyOauthRequest(verifyToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OAuthApi.verifyOauthRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OAuthApi - factory interface
 */
export const OAuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OAuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Create OAuth request
         * @param {OAuthApiCreateOauthRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOauthRequest(requestParameters: OAuthApiCreateOauthRequestRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CreateOauthRequest200Response> {
            return localVarFp.createOauthRequest(requestParameters.createOauthRequestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete OAuth token
         * @param {OAuthApiDeleteOauthTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOauthToken(requestParameters: OAuthApiDeleteOauthTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteOauthToken200Response> {
            return localVarFp.deleteOauthToken(requestParameters.token, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List available OAuth scopes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOauthScopes(options?: RawAxiosRequestConfig): AxiosPromise<GetOauthScopes200Response> {
            return localVarFp.getOauthScopes(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh OAuth token
         * @param {OAuthApiRefreshOauthTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshOauthToken(requestParameters: OAuthApiRefreshOauthTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<VerifyOauthRequest200Response> {
            return localVarFp.refreshOauthToken(requestParameters.refreshOauthTokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify OAuth request
         * @param {OAuthApiVerifyOauthRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyOauthRequest(requestParameters: OAuthApiVerifyOauthRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<VerifyOauthRequest200Response> {
            return localVarFp.verifyOauthRequest(requestParameters.verifyToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OAuthApi - interface
 */
export interface OAuthApiInterface {
    /**
     * 
     * @summary Create OAuth request
     * @param {OAuthApiCreateOauthRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createOauthRequest(requestParameters?: OAuthApiCreateOauthRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateOauthRequest200Response>;

    /**
     * 
     * @summary Delete OAuth token
     * @param {OAuthApiDeleteOauthTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteOauthToken(requestParameters: OAuthApiDeleteOauthTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteOauthToken200Response>;

    /**
     * 
     * @summary List available OAuth scopes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOauthScopes(options?: RawAxiosRequestConfig): AxiosPromise<GetOauthScopes200Response>;

    /**
     * 
     * @summary Refresh OAuth token
     * @param {OAuthApiRefreshOauthTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refreshOauthToken(requestParameters: OAuthApiRefreshOauthTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<VerifyOauthRequest200Response>;

    /**
     * 
     * @summary Verify OAuth request
     * @param {OAuthApiVerifyOauthRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    verifyOauthRequest(requestParameters: OAuthApiVerifyOauthRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<VerifyOauthRequest200Response>;

}

/**
 * Request parameters for createOauthRequest operation in OAuthApi.
 */
export interface OAuthApiCreateOauthRequestRequest {
    /**
     * OAuth create payload
     */
    readonly createOauthRequestRequest?: CreateOauthRequestRequest
}

/**
 * Request parameters for deleteOauthToken operation in OAuthApi.
 */
export interface OAuthApiDeleteOauthTokenRequest {
    /**
     * OAuth token
     */
    readonly token: string
}

/**
 * Request parameters for refreshOauthToken operation in OAuthApi.
 */
export interface OAuthApiRefreshOauthTokenRequest {
    /**
     * OAuth refresh payload
     */
    readonly refreshOauthTokenRequest: RefreshOauthTokenRequest
}

/**
 * Request parameters for verifyOauthRequest operation in OAuthApi.
 */
export interface OAuthApiVerifyOauthRequestRequest {
    /**
     * Verify token from OAuth create response
     */
    readonly verifyToken: string
}

/**
 * OAuthApi - object-oriented interface
 */
export class OAuthApi extends BaseAPI implements OAuthApiInterface {
    /**
     * 
     * @summary Create OAuth request
     * @param {OAuthApiCreateOauthRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOauthRequest(requestParameters: OAuthApiCreateOauthRequestRequest = {}, options?: RawAxiosRequestConfig) {
        return OAuthApiFp(this.configuration).createOauthRequest(requestParameters.createOauthRequestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete OAuth token
     * @param {OAuthApiDeleteOauthTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteOauthToken(requestParameters: OAuthApiDeleteOauthTokenRequest, options?: RawAxiosRequestConfig) {
        return OAuthApiFp(this.configuration).deleteOauthToken(requestParameters.token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List available OAuth scopes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOauthScopes(options?: RawAxiosRequestConfig) {
        return OAuthApiFp(this.configuration).getOauthScopes(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh OAuth token
     * @param {OAuthApiRefreshOauthTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public refreshOauthToken(requestParameters: OAuthApiRefreshOauthTokenRequest, options?: RawAxiosRequestConfig) {
        return OAuthApiFp(this.configuration).refreshOauthToken(requestParameters.refreshOauthTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify OAuth request
     * @param {OAuthApiVerifyOauthRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public verifyOauthRequest(requestParameters: OAuthApiVerifyOauthRequestRequest, options?: RawAxiosRequestConfig) {
        return OAuthApiFp(this.configuration).verifyOauthRequest(requestParameters.verifyToken, options).then((request) => request(this.axios, this.basePath));
    }
}

