/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateDnsRecord200Response } from '../models';
// @ts-ignore
import type { CreateVehicleEventRequest } from '../models';
// @ts-ignore
import type { FinalizeVehicleEventRequest } from '../models';
// @ts-ignore
import type { SetPreferredVehicleRequest } from '../models';
/**
 * VehicleApi - axios parameter creator
 */
export const VehicleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create vehicle event without receipt image
         * @param {CreateVehicleEventRequest} createVehicleEventRequest Vehicle event create payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVehicleEvent: async (createVehicleEventRequest: CreateVehicleEventRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createVehicleEventRequest' is not null or undefined
            assertParamExists('createVehicleEvent', 'createVehicleEventRequest', createVehicleEventRequest)
            const localVarPath = `/vehicle/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createVehicleEventRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete vehicle event
         * @param {number} eventId Vehicle event ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVehicleEvent: async (eventId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('deleteVehicleEvent', 'eventId', eventId)
            const localVarPath = `/vehicle/events/{eventId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finalize vehicle event draft
         * @param {number} eventId Vehicle event ID
         * @param {FinalizeVehicleEventRequest} finalizeVehicleEventRequest Vehicle event finalize payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finalizeVehicleEvent: async (eventId: number, finalizeVehicleEventRequest: FinalizeVehicleEventRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('finalizeVehicleEvent', 'eventId', eventId)
            // verify required parameter 'finalizeVehicleEventRequest' is not null or undefined
            assertParamExists('finalizeVehicleEvent', 'finalizeVehicleEventRequest', finalizeVehicleEventRequest)
            const localVarPath = `/vehicle/events/{eventId}/finalize`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(finalizeVehicleEventRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get vehicle event detail
         * @param {number} eventId Vehicle event ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVehicleEvent: async (eventId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('getVehicleEvent', 'eventId', eventId)
            const localVarPath = `/vehicle/events/{eventId}`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get event image or thumbnail
         * @param {number} eventId Vehicle event ID
         * @param {string} [size] Image size variant: thumb, thumbnail or small for thumbnail response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVehicleEventImage: async (eventId: number, size?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('getVehicleEventImage', 'eventId', eventId)
            const localVarPath = `/vehicle/events/{eventId}/image`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = 'image/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List currencies for vehicle events
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVehicleCurrencies: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vehicle/currencies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List vehicle events for the authenticated driver
         * @param {string} [since] Return events with event datetime greater than or equal to the provided local datetime
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVehicleEvents: async (since?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vehicle/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (since !== undefined) {
                localVarQueryParameter['since'] = since;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List vehicles available to the authenticated driver
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVehicleVehicles: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vehicle/vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Replace event image and rescan event data
         * @param {number} eventId Vehicle event ID
         * @param {File} image 
         * @param {string} [timezone] 
         * @param {string} [eventType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rescanVehicleEventImage: async (eventId: number, image: File, timezone?: string, eventType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'eventId' is not null or undefined
            assertParamExists('rescanVehicleEventImage', 'eventId', eventId)
            // verify required parameter 'image' is not null or undefined
            assertParamExists('rescanVehicleEventImage', 'image', image)
            const localVarPath = `/vehicle/events/{eventId}/image`
                .replace(`{${"eventId"}}`, encodeURIComponent(String(eventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }

            if (timezone !== undefined) { 
                localVarFormParams.append('timezone', timezone as any);
            }

            if (eventType !== undefined) { 
                localVarFormParams.append('eventType', eventType as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Set or clear preferred vehicle
         * @param {SetPreferredVehicleRequest} [setPreferredVehicleRequest] Preferred vehicle payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setPreferredVehicle: async (setPreferredVehicleRequest?: SetPreferredVehicleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vehicle/preferred-vehicle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setPreferredVehicleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload receipt image and create processing event draft
         * @param {File} image 
         * @param {string} timezone 
         * @param {string} [eventType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadVehicleReceiptImage: async (image: File, timezone: string, eventType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'image' is not null or undefined
            assertParamExists('uploadVehicleReceiptImage', 'image', image)
            // verify required parameter 'timezone' is not null or undefined
            assertParamExists('uploadVehicleReceiptImage', 'timezone', timezone)
            const localVarPath = `/vehicle/events/receipt-image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }

            if (timezone !== undefined) { 
                localVarFormParams.append('timezone', timezone as any);
            }

            if (eventType !== undefined) { 
                localVarFormParams.append('eventType', eventType as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VehicleApi - functional programming interface
 */
export const VehicleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VehicleApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create vehicle event without receipt image
         * @param {CreateVehicleEventRequest} createVehicleEventRequest Vehicle event create payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVehicleEvent(createVehicleEventRequest: CreateVehicleEventRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVehicleEvent(createVehicleEventRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.createVehicleEvent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete vehicle event
         * @param {number} eventId Vehicle event ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteVehicleEvent(eventId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteVehicleEvent(eventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.deleteVehicleEvent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Finalize vehicle event draft
         * @param {number} eventId Vehicle event ID
         * @param {FinalizeVehicleEventRequest} finalizeVehicleEventRequest Vehicle event finalize payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finalizeVehicleEvent(eventId: number, finalizeVehicleEventRequest: FinalizeVehicleEventRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finalizeVehicleEvent(eventId, finalizeVehicleEventRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.finalizeVehicleEvent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get vehicle event detail
         * @param {number} eventId Vehicle event ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVehicleEvent(eventId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVehicleEvent(eventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.getVehicleEvent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get event image or thumbnail
         * @param {number} eventId Vehicle event ID
         * @param {string} [size] Image size variant: thumb, thumbnail or small for thumbnail response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVehicleEventImage(eventId: number, size?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVehicleEventImage(eventId, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.getVehicleEventImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List currencies for vehicle events
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVehicleCurrencies(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVehicleCurrencies(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.listVehicleCurrencies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List vehicle events for the authenticated driver
         * @param {string} [since] Return events with event datetime greater than or equal to the provided local datetime
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVehicleEvents(since?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVehicleEvents(since, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.listVehicleEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List vehicles available to the authenticated driver
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVehicleVehicles(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVehicleVehicles(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.listVehicleVehicles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Replace event image and rescan event data
         * @param {number} eventId Vehicle event ID
         * @param {File} image 
         * @param {string} [timezone] 
         * @param {string} [eventType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rescanVehicleEventImage(eventId: number, image: File, timezone?: string, eventType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rescanVehicleEventImage(eventId, image, timezone, eventType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.rescanVehicleEventImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Set or clear preferred vehicle
         * @param {SetPreferredVehicleRequest} [setPreferredVehicleRequest] Preferred vehicle payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setPreferredVehicle(setPreferredVehicleRequest?: SetPreferredVehicleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setPreferredVehicle(setPreferredVehicleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.setPreferredVehicle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload receipt image and create processing event draft
         * @param {File} image 
         * @param {string} timezone 
         * @param {string} [eventType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadVehicleReceiptImage(image: File, timezone: string, eventType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDnsRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadVehicleReceiptImage(image, timezone, eventType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VehicleApi.uploadVehicleReceiptImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VehicleApi - factory interface
 */
export const VehicleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VehicleApiFp(configuration)
    return {
        /**
         * 
         * @summary Create vehicle event without receipt image
         * @param {VehicleApiCreateVehicleEventRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVehicleEvent(requestParameters: VehicleApiCreateVehicleEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.createVehicleEvent(requestParameters.createVehicleEventRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete vehicle event
         * @param {VehicleApiDeleteVehicleEventRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVehicleEvent(requestParameters: VehicleApiDeleteVehicleEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.deleteVehicleEvent(requestParameters.eventId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finalize vehicle event draft
         * @param {VehicleApiFinalizeVehicleEventRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finalizeVehicleEvent(requestParameters: VehicleApiFinalizeVehicleEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.finalizeVehicleEvent(requestParameters.eventId, requestParameters.finalizeVehicleEventRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get vehicle event detail
         * @param {VehicleApiGetVehicleEventRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVehicleEvent(requestParameters: VehicleApiGetVehicleEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.getVehicleEvent(requestParameters.eventId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get event image or thumbnail
         * @param {VehicleApiGetVehicleEventImageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVehicleEventImage(requestParameters: VehicleApiGetVehicleEventImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.getVehicleEventImage(requestParameters.eventId, requestParameters.size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List currencies for vehicle events
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVehicleCurrencies(options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.listVehicleCurrencies(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List vehicle events for the authenticated driver
         * @param {VehicleApiListVehicleEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVehicleEvents(requestParameters: VehicleApiListVehicleEventsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.listVehicleEvents(requestParameters.since, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List vehicles available to the authenticated driver
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVehicleVehicles(options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.listVehicleVehicles(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Replace event image and rescan event data
         * @param {VehicleApiRescanVehicleEventImageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rescanVehicleEventImage(requestParameters: VehicleApiRescanVehicleEventImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.rescanVehicleEventImage(requestParameters.eventId, requestParameters.image, requestParameters.timezone, requestParameters.eventType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Set or clear preferred vehicle
         * @param {VehicleApiSetPreferredVehicleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setPreferredVehicle(requestParameters: VehicleApiSetPreferredVehicleRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.setPreferredVehicle(requestParameters.setPreferredVehicleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload receipt image and create processing event draft
         * @param {VehicleApiUploadVehicleReceiptImageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadVehicleReceiptImage(requestParameters: VehicleApiUploadVehicleReceiptImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response> {
            return localVarFp.uploadVehicleReceiptImage(requestParameters.image, requestParameters.timezone, requestParameters.eventType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VehicleApi - interface
 */
export interface VehicleApiInterface {
    /**
     * 
     * @summary Create vehicle event without receipt image
     * @param {VehicleApiCreateVehicleEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createVehicleEvent(requestParameters: VehicleApiCreateVehicleEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Delete vehicle event
     * @param {VehicleApiDeleteVehicleEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteVehicleEvent(requestParameters: VehicleApiDeleteVehicleEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Finalize vehicle event draft
     * @param {VehicleApiFinalizeVehicleEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    finalizeVehicleEvent(requestParameters: VehicleApiFinalizeVehicleEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Get vehicle event detail
     * @param {VehicleApiGetVehicleEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getVehicleEvent(requestParameters: VehicleApiGetVehicleEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Get event image or thumbnail
     * @param {VehicleApiGetVehicleEventImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getVehicleEventImage(requestParameters: VehicleApiGetVehicleEventImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<File>;

    /**
     * 
     * @summary List currencies for vehicle events
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listVehicleCurrencies(options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary List vehicle events for the authenticated driver
     * @param {VehicleApiListVehicleEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listVehicleEvents(requestParameters?: VehicleApiListVehicleEventsRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary List vehicles available to the authenticated driver
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listVehicleVehicles(options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Replace event image and rescan event data
     * @param {VehicleApiRescanVehicleEventImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rescanVehicleEventImage(requestParameters: VehicleApiRescanVehicleEventImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Set or clear preferred vehicle
     * @param {VehicleApiSetPreferredVehicleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setPreferredVehicle(requestParameters?: VehicleApiSetPreferredVehicleRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

    /**
     * 
     * @summary Upload receipt image and create processing event draft
     * @param {VehicleApiUploadVehicleReceiptImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadVehicleReceiptImage(requestParameters: VehicleApiUploadVehicleReceiptImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDnsRecord200Response>;

}

/**
 * Request parameters for createVehicleEvent operation in VehicleApi.
 */
export interface VehicleApiCreateVehicleEventRequest {
    /**
     * Vehicle event create payload
     */
    readonly createVehicleEventRequest: CreateVehicleEventRequest
}

/**
 * Request parameters for deleteVehicleEvent operation in VehicleApi.
 */
export interface VehicleApiDeleteVehicleEventRequest {
    /**
     * Vehicle event ID
     */
    readonly eventId: number
}

/**
 * Request parameters for finalizeVehicleEvent operation in VehicleApi.
 */
export interface VehicleApiFinalizeVehicleEventRequest {
    /**
     * Vehicle event ID
     */
    readonly eventId: number

    /**
     * Vehicle event finalize payload
     */
    readonly finalizeVehicleEventRequest: FinalizeVehicleEventRequest
}

/**
 * Request parameters for getVehicleEvent operation in VehicleApi.
 */
export interface VehicleApiGetVehicleEventRequest {
    /**
     * Vehicle event ID
     */
    readonly eventId: number
}

/**
 * Request parameters for getVehicleEventImage operation in VehicleApi.
 */
export interface VehicleApiGetVehicleEventImageRequest {
    /**
     * Vehicle event ID
     */
    readonly eventId: number

    /**
     * Image size variant: thumb, thumbnail or small for thumbnail response
     */
    readonly size?: string
}

/**
 * Request parameters for listVehicleEvents operation in VehicleApi.
 */
export interface VehicleApiListVehicleEventsRequest {
    /**
     * Return events with event datetime greater than or equal to the provided local datetime
     */
    readonly since?: string
}

/**
 * Request parameters for rescanVehicleEventImage operation in VehicleApi.
 */
export interface VehicleApiRescanVehicleEventImageRequest {
    /**
     * Vehicle event ID
     */
    readonly eventId: number

    readonly image: File

    readonly timezone?: string

    readonly eventType?: string
}

/**
 * Request parameters for setPreferredVehicle operation in VehicleApi.
 */
export interface VehicleApiSetPreferredVehicleRequest {
    /**
     * Preferred vehicle payload
     */
    readonly setPreferredVehicleRequest?: SetPreferredVehicleRequest
}

/**
 * Request parameters for uploadVehicleReceiptImage operation in VehicleApi.
 */
export interface VehicleApiUploadVehicleReceiptImageRequest {
    readonly image: File

    readonly timezone: string

    readonly eventType?: string
}

/**
 * VehicleApi - object-oriented interface
 */
export class VehicleApi extends BaseAPI implements VehicleApiInterface {
    /**
     * 
     * @summary Create vehicle event without receipt image
     * @param {VehicleApiCreateVehicleEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createVehicleEvent(requestParameters: VehicleApiCreateVehicleEventRequest, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).createVehicleEvent(requestParameters.createVehicleEventRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete vehicle event
     * @param {VehicleApiDeleteVehicleEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteVehicleEvent(requestParameters: VehicleApiDeleteVehicleEventRequest, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).deleteVehicleEvent(requestParameters.eventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Finalize vehicle event draft
     * @param {VehicleApiFinalizeVehicleEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public finalizeVehicleEvent(requestParameters: VehicleApiFinalizeVehicleEventRequest, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).finalizeVehicleEvent(requestParameters.eventId, requestParameters.finalizeVehicleEventRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get vehicle event detail
     * @param {VehicleApiGetVehicleEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getVehicleEvent(requestParameters: VehicleApiGetVehicleEventRequest, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).getVehicleEvent(requestParameters.eventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get event image or thumbnail
     * @param {VehicleApiGetVehicleEventImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getVehicleEventImage(requestParameters: VehicleApiGetVehicleEventImageRequest, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).getVehicleEventImage(requestParameters.eventId, requestParameters.size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List currencies for vehicle events
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listVehicleCurrencies(options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).listVehicleCurrencies(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List vehicle events for the authenticated driver
     * @param {VehicleApiListVehicleEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listVehicleEvents(requestParameters: VehicleApiListVehicleEventsRequest = {}, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).listVehicleEvents(requestParameters.since, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List vehicles available to the authenticated driver
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listVehicleVehicles(options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).listVehicleVehicles(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Replace event image and rescan event data
     * @param {VehicleApiRescanVehicleEventImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public rescanVehicleEventImage(requestParameters: VehicleApiRescanVehicleEventImageRequest, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).rescanVehicleEventImage(requestParameters.eventId, requestParameters.image, requestParameters.timezone, requestParameters.eventType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Set or clear preferred vehicle
     * @param {VehicleApiSetPreferredVehicleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setPreferredVehicle(requestParameters: VehicleApiSetPreferredVehicleRequest = {}, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).setPreferredVehicle(requestParameters.setPreferredVehicleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload receipt image and create processing event draft
     * @param {VehicleApiUploadVehicleReceiptImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadVehicleReceiptImage(requestParameters: VehicleApiUploadVehicleReceiptImageRequest, options?: RawAxiosRequestConfig) {
        return VehicleApiFp(this.configuration).uploadVehicleReceiptImage(requestParameters.image, requestParameters.timezone, requestParameters.eventType, options).then((request) => request(this.axios, this.basePath));
    }
}

