/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ChangeDomainNameserversRequest {
    'cname'?: string;
    'dns_servers_opt'?: string;
    'ns'?: Array<string>;
    'ns1'?: string;
    'ns1_ipv4'?: string;
    'ns1_ipv6'?: string;
    'ns2'?: string;
    'ns2_ipv4'?: string;
    'ns2_ipv6'?: string;
    'ns3'?: string;
    'ns3_ipv4'?: string;
    'ns3_ipv6'?: string;
    'ns4'?: string;
    'ns4_ipv4'?: string;
    'ns4_ipv6'?: string;
}

