/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FinalizeVehicleEventRequestFueling } from './finalize-vehicle-event-request-fueling';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalizeVehicleEventRequestLocation } from './finalize-vehicle-event-request-location';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalizeVehicleEventRequestMoney } from './finalize-vehicle-event-request-money';

export interface CreateVehicleEventRequest {
    'eventType': string;
    'datetimeLocal': string;
    'timezone': string;
    'location': FinalizeVehicleEventRequestLocation;
    'vehicleId'?: string;
    'purpose'?: string;
    'notes'?: string;
    'odometer'?: number;
    'money'?: FinalizeVehicleEventRequestMoney;
    'fueling'?: FinalizeVehicleEventRequestFueling;
}

