/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GetDnsRecords200ResponseDataRecordsInner {
    'record_id'?: number;
    'type'?: string;
    'name'?: string;
    'content'?: string;
    'ttl'?: number;
    'prio'?: number;
}

