/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetDnsRecords200ResponseData } from './get-dns-records200-response-data';

export interface GetDnsRecords200Response {
    'status': string;
    'retval': number;
    'msg': string;
    'data': GetDnsRecords200ResponseData;
    'requestId': number;
}

