/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetDnsRecords200ResponseDataRecordsInner } from './get-dns-records200-response-data-records-inner';

export interface GetDnsRecords200ResponseData {
    'domain_id'?: number;
    'domain'?: string;
    'master'?: string;
    'type'?: string;
    'records'?: Array<GetDnsRecords200ResponseDataRecordsInner>;
}

