/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetOauthScopes200ResponseDataInner } from './get-oauth-scopes200-response-data-inner';

export interface GetOauthScopes200Response {
    'status': string;
    'retval': number;
    'msg': string;
    'data': Array<GetOauthScopes200ResponseDataInner>;
    'requestId': number;
}

