/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MergeCartItems200ResponseData {
    'status'?: string;
    'merged'?: boolean;
    'from_cname'?: string;
    'to_cname'?: string;
    'moved_items'?: number;
    'merged_items'?: number;
    'items_count'?: number;
}

