/* tslint:disable */
/* eslint-disable */
/**
 * Platon OpenAPI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SpamDetection200ResponseData {
    /**
     * Normalized classification returned by the LLM.
     */
    'classification': SpamDetection200ResponseDataClassificationEnum;
    /**
     * Normalized confidence from 0 to 100.
     */
    'confidence': number;
    /**
     * Short explanation in Slovak.
     */
    'reason': string;
    /**
     * Most important signals used for the classification.
     */
    'signals': Array<string>;
    /**
     * True when the LLM call or response validation failed.
     */
    'error': boolean;
    /**
     * Short technical error reason. Raw LLM response is never returned here.
     */
    'error_message': string;
}

export enum SpamDetection200ResponseDataClassificationEnum {
    Spam = 'spam',
    Ham = 'ham',
    Unknown = 'unknown',
    UnknownDefaultOpenApi = '11184809'
}


